# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pro', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
    ]
